{% set version = "1.2.3" %}

package:
  name: bactopia
  version: {{ version }}

build:
  number: 0
  noarch: generic

source:
  url: https://github.com/bactopia/bactopia/archive/v{{version}}.tar.gz
  sha256: 538a69d0e4157e5e41525c9e981cda8bf78e5bdefe55e17327965c87632dd290

requirements:
  host:
  run:
    - ariba
    - beautifulsoup4
    - biopython
    - blast
    - cd-hit
    #- conda
    - executor
    - lxml
    - mash
    - ncbi-genome-download
    - nextflow
    - pysam >=0.15.3 # older versions have wrong openssl pinning
    - python >3.6
    - requests 
    - unzip
    - wget

test:
  commands:
    - "bactopia --help"
    - "bactopia --version"
    - "bactopia datasets"
    - "bactopia prepare"
    - "bactopia search"

about:
  home: https://github.com/bactopia/bactopia
  license: MIT
  license_file: LICENSE
  summary: Bactopia is an extensive workflow to process Illumina sequencing of bacterial genomes.
