{% set name = "chromatiblock" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: generic
  number: 0
  script: mkdir -p ${PREFIX}/bin && cp chromatiblock.py ${PREFIX}/bin && chmod +x ${PREFIX}/bin/*

source:
  url: https://github.com/mjsull/chromatiblock/archive/v{{ version }}.tar.gz
  sha256: fb2155a3d2df0ee96b127edec0d604dc706478e1788708b3bc33d2c076d6529a

requirements:
  run:
    - python >=3
    - Sibelia
    - blast >=2.2
    - cairosvg
    
test:
  commands:
    - chromatiblock.py -h

about:
  home: http://github.com/mjsull/chromatiblock/
  license: GPLv3
  license_file: LICENSE.md
  summary: Scalable, whole-genome visualisation of structural changes in prokaryotes.
