{% set name = "phate" %}
{% set version = "1.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91f288e941e27573f14638d9da6cc593d059df6c935e3a5005d6a48d2d3ce262

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy >=1.16.0
    - python >=3.5
    - scikit-learn >=0.20.0
    - scipy >=1.1.0
    - future
    - tasklogger >=1.0
    - graphtools >=1.3.1
    - scprep >=1.0
    - matplotlib >=3.0
    - deprecated
    - sgdpy >=1.4.1

test:
  imports:
    - phate

about:
  home: https://github.com/KrishnaswamyLab/PHATE
  license: GNU General Public Version 2
  license_file: LICENSE
  license_family: GPL2
  summary: PHATE (Potential of Heat-diffusion for Affinity-based Transition Embedding) is a tool for visualizing high dimensional data.
