{% set name = "phate" %}
{% set version = "1.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1f4570dad9521fc30d8185ba50417dc447e878569e54c98af734d03be0860418

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  noarch: python

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - numpy >=1.14.0
    - python >=3.5
    - scikit-learn >=0.20.0
    - scipy >=1.1.0
    - future
    - tasklogger >=1.0
    - graphtools >=1.3.1
    - scprep >=0.11.1
    - matplotlib >=3.0

test:
  imports:
    - phate

about:
  home: https://github.com/KrishnaswamyLab/PHATE
  license: GNU General Public Version 2
  license_family: GPL2
  summary: PHATE (Potential of Heat-diffusion for Affinity-based Transition Embedding) is a tool for visualizing high dimensional data.
