{% set name = "busco" %}
{% set version = "4.0.beta1" %}
{% set sha256 = "9eb9f12eb6c7a68e15048ff0b6e9b4f783ce96cd56ffa5f6df51f381e06ade88" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: python


source:
  url: https://gitlab.com/ezlab/busco/-/archive/{{ version }}/busco-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - findutils
    - blast >=2.2,<2.4
    - hmmer >=3.2.1
    - augustus >=3.3.2
    - r-base
    - r-ggplot2 >=2.2.1
    - prodigal =3.6
    - sepp =4.3.10

test:
  requires:
    - wget
  commands:
    - run_BUSCO.py -h
    - run_busco -h
    - generate_plot.py -h
    - generate_plot -h
    - mkdir findtest ; cd findtest ; touch file ; find . -delete ; cd ..

    # Message reported by busco when the config file exists but no input provided
    - run_busco | grep "Please add it in the config file"

about:
  home: http://busco.ezlab.org/
  license: GPL
  summary: BUSCO provides measures for quantitative assessment of genome
           assembly, gene set, and transcriptome completeness based on
           evolutionarily informed expectations of gene content from
           near-universal single-copy orthologs selected from OrthoDB.

extra:
  identifiers:
    - biotools:busco
    - doi:10.1093/bioinformatics/btv351
  recipe-maintainers:
    - silask
    - matsepp
