{% set name = "dfba" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ced1dc0be18e5012e20efac39bab58e2248e4e581eb1ee65e17be9274af3efdf

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: The package home page
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: 
  summary: "Object-oriented software for dynamic flux-balance simulations."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
