{% set name = "dfba" %}
{% set version = "0.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: d4d5e813ca0d4afb4d609470e9a06153a0938851519e8d53df9c55f7cb70f5b0

build:
  number: 0
  script: "{{ PYTHON }} -m pip install -vv --no-deps --ignore-installed ."

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - {{ compiler('cxx') }}
    - glpk >=4.65
    - pkg-config
    - pybind11
    - python ==3.7
    - sundials >=5.0
  run:
    - cobra
    - {{ compiler('cxx') }}
    - depinfo
    - glpk >=4.65
    - optlang
    - pandas
    - python ==3.7
    - sundials >=5.0
    - symengine
    - sympy

test:
  imports:
    - dfba

about:
  home: https://dynamic-fba.readthedocs.io
  license: "GNU General Public v3 or later (GPLv3+)"
  license_family: GPL3
  license_file: LICENSE.md
  summary: "Object-oriented software for dynamic flux-balance analysis (DFBA) simulations."
  description: |
    This project provides an object-oriented software package for dynamic
    flux-balance analysis (DFBA) simulations using implementations of the direct
    method or Algorithm 1 described in the paper Harwood et al., 2016. The main
    algorithms for solving embedded LP problems are written in C++ and use the
    GNU Linear Programming Kit (GLPK) and the Suite of Nonlinear and
    Differential/Algebraic Equation Solvers (SUNDIALS) CVODE or IDA. Extension
    modules to cobrapy are provided for easy generation and simulation of DFBA
    models.
  doc_url: https://dynamic-fba.readthedocs.io
  dev_url: https://gitlab.com/davidtourigny/dynamic-fba

extra:
  recipe-maintainers:
    - Midnighter
    - davidtourigny
